
#ifdef THIR_EXTENSIONS

#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>0
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(0, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>1
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(1, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>2
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(2, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>3
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(3, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>4
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(4, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>5
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(5, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>6
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(6, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>7
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(7, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>8
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(8, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif
#  if BOOST_PP_SEQ_SIZE(THIR_EXTENSIONS)>9
#    include THIR_EXTENSION_INCLUDE(BOOST_PP_SEQ_ELEM(9, THIR_EXTENSIONS), THIR_EXTENSION_CLASS, THIR_EXTENSION_TYPE)
#  endif


#endif

#undef THIR_EXTENSION_TYPE
#undef THIR_EXTENSION_CLASS
