language: cpp

git:
  submodules: false

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libboost-dev
      - qtbase5-dev

script: 
  -  git submodule update --init googletest && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && ./tests_big && ./tests_little && ./test_extension_qt
