language: cpp

compiler:
  - clang
  - gcc

addons: 
  apt: 
    packages: libboost-all-dev

script: 
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && ./tests_big && ./tests_little
