name: C/C++ CI

on: [push]

jobs:
  build:
    
    strategy:
      matrix:
        os: ['windows-2016', 'windows-2019', 'macOS-latest']

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      if: runner.os != 'Windows'
    - name: install conan
      run: |
        pip install conan
        conan install .
    - name: Build and test
      uses: lukka/run-cmake@v0.10
      with:
        cmakeBuildType: Release
        cmakeAppendedArgs: -DDISABLE_QT_TEST:bool=${{ runner.os == 'Windows' }}
        buildWithCMakeArgs: --target test
    
